# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprof.User'),
        ),
    ]
