# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ACAD', 'Academic'), ('NACAD', 'Non-Academic')], default='ACAD', max_length=5),
        ),
    ]
