# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0006_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_condition',
            field=models.CharField(choices=[('USED', 'Used'), ('BNEW', 'Brand New')], default='BNEW', max_length=4),
        ),
    ]
