# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0008_profile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='academic_subject',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
