# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0010_auto_20170731_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_condition',
            field=models.CharField(choices=[('USED', 'Used'), ('Brand New', 'BNEW')], default='BNEW', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
