# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0015_auto_20170811_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
