# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0017_auto_20170813_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='offers',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_item', to='userprof.Post'),
        ),
    ]
